### ISSUE TITLE
cmif tweaks

### ISSUE THREAD

**Issue by csae8092** [emt-project/emt-static#101]
* > `<editor>Euer Kontakt<email>kontakt@example.com</email></editor>` in titleStmt.
* > warum momentan erst so wenige Orte angegeben sind
* > warum nur die Eleonorabriefe drinnen sind (zumindest sieht es jetzt bei der Anzahl von ca. 1200 so aus, auf der Website haben wir ja ca. 1600).
* >  ein Beistrich fehlt in den Angaben, nämlich zwischen „geb. Pfalz-Neuburg“ und „an Johann Wilhelm…“.

**Comment by csae8092** [comment]
following files are exlcuded; mainly because of unknown or not gnd-referenced persons
data/editions/kasten_blau_44_6_0109.xml
data/editions/kasten_blau_45_7_0053.xml
data/editions/kasten_blau_44_6_0350.xml
data/editions/kasten_blau_44_7_0096.xml
data/editions/korrespondenzakten_1147_0021.xml
data/editions/kasten_blau_45_15_0348.xml
data/editions/kasten_blau_45_15_0104.xml
data/editions/kasten_blau_45_15_0449.xml
data/editions/kasten_blau_44_6_0473.xml
data/editions/korrespondenzakten_1147_0181.xml
data/editions/kasten_blau_45_15_0106.xml
data/editions/kasten_blau_44_7_0094.xml
data/editions/kasten_blau_44_8_0004.xml
data/editions/emt___77-8806c.xml
data/editions/kasten_blau_45_15_0407.xml
data/editions/kasten_blau_44_10_0217.xml
data/editions/kasten_blau_45_7_0052.xml
17

**Comment by SpitzbartAnna** [comment]
Soweit möglich Daten ergänzt, in manchen Fällen jedoch nicht möglich. Es verbleiben ungelöst:

data/editions/kasten_blau_45_7_0053.xml -> Ort unklar
data/editions/kasten_blau_45_15_0348.xml ->| nicht zuzuordnen
data/editions/kasten_blau_44_6_0473.xml |  
data/editions/kasten_blau_44_10_0217.xml -> Zeitung ohne Angaben
data/editions/kasten_blau_45_7_0052.xml -> Unklar, an wen gerichtet und wann
