### ISSUE TITLE
fix logos

### ISSUE THREAD

**Issue by skurzinz** [emt-project/emt-static#14]
before this goes public public, pls revise the logos

- fwf has a new logo 
- the ihb logo given uses a wrong font and alignment
  - ihb paid an external graphics person to do a logo, this is on ihb's share
  - öffentlichkeitsarbeit dept should approve of the used solution

**Comment by skurzinz** [comment]
![Logo_ihb_en_RGB](https://github.com/emt-project/emt-static/assets/37441365/6e1c7f40-fb61-4cb8-bfd0-32f7e3725a45)

For your eyes' delight.

**Comment by csae8092** [comment]
closed with https://github.com/emt-project/emt-static/commit/353568b861a50c80ba53f5f6a0ddc491375ba209
