### ISSUE TITLE
find a solution to merge imprints

### ISSUE THREAD

**Issue by csae8092** [emt-project/emt-static#35]

**Comment by csae8092** [comment]
partly resolved, but needs fixing here https://github.com/acdh-oeaw/acdh-common-assets/issues/11 as well

**Comment by ttechnicus** [comment]
ImprintParams refreshed on page https://redmine.acdh.oeaw.ac.at/issues/21311
Tested at https://shared.acdh.oeaw.ac.at/acdh-common-assets/api/imprint.php?serviceID=21311
yaml contents saved in file `redmine_issues_21311_ImprintParams.yml` for version control.

**Comment by ttechnicus** [comment]
yaml file containing the copy of redmine form contents was only saved in the branch `35-find-a-solution-to-merge-imprints`, but not merged.
