### ISSUE TITLE
text-image-line-highlighting no longer working for all documents

### ISSUE THREAD

**Issue by csae8092** [emt-project/emt-static#43]
please investigate why the image hihglighting stopped working here https://emt.acdh-dev.oeaw.ac.at/kasten_blau_45_8_0051.html (console prompts following error msg: `Uncaught TypeError: openViewer is undefined`

but still works here: https://emt.acdh-dev.oeaw.ac.at/emt___77-8811-korrespondenz-kurfursten-2.html

**Comment by csae8092** [comment]
looks like only kasten_blau_45_8... are not working

**Comment by ttechnicus** [comment]
Explanation of solution (hats off to Daniel Elsner [Stoxreiter]): the osd viewers of the pages were numbered by position, while the line numbers' click event calculated the viewer ID from the "facs" number of the page which equals its position on the page, but is different in files kasten_blau_45_8*

ViewerId is now generated based on the first <pb> element's @facs attribute.
