### ISSUE TITLE
Paratext formatting

### ISSUE THREAD

**Issue by ttechnicus** [emt-project/emt-static#44]
Broken parts of html elements appear in paratexts
E.g. chiffre.html shows:

> style="text-align: justify;">Zur zusätzlichen Verschlüsselung wurden zudem spezielle Symbole für bestimmte Personen (bspw. den spanischen König) verwendet sowie der Deckname „Tiberius“ für Johann Wilhelm (vgl. dazu das anliegende Chiffrenalphabet und die Tabelle für Sonderzeichen). Einige wenige dieser Symbole sind noch nicht aufgelöst, dürften jedoch im Zusammenhang mit dem spanischen Erbfolgekrieg stehen.
>
> style="text-align: justify;">Weiterführend dazu die Editionsrichtlinien sowie der folgende Blogbeitrag: Kaiserliche Geheimnisse. Ein Blick auf den Chiffrengebrauch in der Korrespondenz Eleonora Magdalena Theresias | Kaiserin und Reich (hypotheses.org)

**Comment by csae8092** [comment]
seems to be fixed by @SpitzbartAnna with https://github.com/emt-project/emt-para-text/commit/93d35520f4d0952bc115f6f1b85046a7ebaf4882
