### ISSUE TITLE
feature: legend for calendar

### ISSUE THREAD

**Issue by csae8092** [emt-project/emt-static#54]
provide a small legend in the calendar explaining the used colors

**Comment by ttechnicus** [comment]
Please provide the German text for the following:
- "Explanation of colors" (or "legend")
- "Red: extant letter"
- "Green: letter referenced by date in another letter"
- "Black: more than 3 letters"

**Comment by csae8092** [comment]
- [ ] please move the legend into the modal triggered by the info button 

![image](https://github.com/emt-project/emt-static/assets/7540477/649c3047-c984-442c-9037-f7cb6010b102)

- [ ] please try to get rid of `"Black: more than 3 letters"` because IMHO it makes not much sense why there should be different behavior (my best guess is this is due to some legacy code);

**Comment by ttechnicus** [comment]
@csae8092 Ad 1) This must be the behaviour of the Calendar class, as I see no code on our side that would affect this. In fact I had to figure out the meaning of the black color by user testing, as the black colour does not occur in our code either.

**Comment by ttechnicus** [comment]
Got it
https://unpkg.com/js-year-calendar@2.0.0/dist/js-year-calendar.js
Line 734, or search for "black" (only one occurrence)

**Comment by SpitzbartAnna** [comment]
> @csae8092 Please provide the German text for the following:
> 
> * "Explanation of colors" (or "legend")
> * "Red: extant letter"
> * "Green: letter referenced by date in another letter"
> * "Black: more than 3 letters"

Legende (Farben)
Rot: Brief liegt vor
Grün: Brief wird in einem vorliegenden Brief referenziert
Schwarz: Mehr als drei Briefe
