### ISSUE TITLE
Improve the calendar legend (various)

### ISSUE THREAD

**Issue by ttechnicus** [emt-project/emt-static#78]
- Add German translation
- Place the info icon so that it is better visible

Referring to [Teams discussion](https://teams.microsoft.com/l/message/19:earu0vKcat422Yhlao52sdWcdho6XR_jMYfKk1K_ndQ1@thread.tacv2/1698243449506?tenantId=ef12f07e-2409-490f-8edc-3bc91a927a71&groupId=b9b3f74f-02df-4d9b-b016-097433b4fdfd&parentMessageId=1698242724796&teamName=ACDH-CH_p_EMT_FamiliensacheHandlungsspielraeumeEleonoraMagdalena&channelName=General&createdTime=1698243449506&allowXTenantAccess=false), bullet point 3).

**Comment by ttechnicus** [comment]
@csae8092 Peter, what is the requirement for the German translation of the legend? 
Should that be controlled by the language selector in the menu? (Is that possible at all?)

**Comment by csae8092** [comment]
> @csae8092 Peter, what is the requirement for the German translation of the legend? Should that be controlled by the language selector in the menu? (Is that possible at all?)

Yes that's how it should be implemented and should be possible

**Comment by csae8092** [comment]
https://github.com/emt-project/emt-static/issues/54

**Comment by ttechnicus** [comment]
Possibly remove black coloring from calendar by follow-up parsing
