### ISSUE TITLE
check if biographies show up

### ISSUE THREAD

**Issue by csae8092** [emt-project/emt-static#79]
also check for images
for Anna ;) please check for whitespaces

@SpitzbartAnna please provide link names which will show up in the menu
-> make a new tab "Biographien/Biographies"
-> decide where, e.g. after Project

**Comment by ttechnicus** [comment]
@SpitzbartAnna Please check the images in the `data/img` folder:
- only leave images there which are referenced in xml files,
- eliminate white spaces and special characters from the file names, and possible use a consistent file extension (e.g. .jpg for all its variants).

**Comment by SpitzbartAnna** [comment]
> also check for images for Anna ;) please check for whitespaces
> 
> @SpitzbartAnna please provide link names which will show up in the menu -> make a new tab "Biographien/Biographies" -> decide where, e.g. after Project

After checking in with Frau Keller, this would be the menu order:
1) Projekt / Über das Projekt, Überlieferung der Quellen, Chiffre, Team, Blog, Quellcode der Applikation

**Comment by ttechnicus** [comment]
Copyright information about the images embedded in the biography texts (coded in //figure/graphic/desc) should appear in the caption of the image.
